echo '----------------------------- VARIABLES ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/variables.sh)
echo '------------------------------ ALIASES -----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/aliases.sh)
echo '----------------------------- FUNCTIONS ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/functions.sh)
echo '---------------------------- AUTOCOMPLETE --------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/autocomplete.sh)
echo '------------------------------- TMUX -------------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/tmux.sh)
echo '------------------------------ BANNER ------------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/banner.sh)
echo '----------------------------- POWERLINE ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/powerline.sh)
