cat '----------------------------- VARIABLES ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/variables.sh)
cat '------------------------------ ALIASES -----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/aliases.sh)
cat '----------------------------- FUNCTIONS ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/functions.sh)
cat '---------------------------- AUTOCOMPLETE --------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/autocomplete.sh)
cat '------------------------------- TMUX -------------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/tmux.sh)
cat '------------------------------ BANNER ------------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/banner.sh)
cat '----------------------------- POWERLINE ----------------------------------'
cat <(curl -s https://raw.githubusercontent.com/tornermarton/toolkit/master/bash/tools/powerline.sh)
